"""add fact_settlement table

Revision ID: 1962879e902d
Revises: 76b94fdde540
Create Date: 2026-10-08 23:26:29.171889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1962879e902d'
down_revision: Union[str, Sequence[str], None] = '76b94fdde540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_settlement',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_settlement_amount_positive'),
    sa.CheckConstraint('from_user_id <> to_user_id', name='ck_settlement_distinct_users'),
    sa.ForeignKeyConstraint(['from_user_id'], ['dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_index(op.f('ix_fact_settlement_settlement_id'), 'fact_settlement', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_settlement_settlement_id'), table_name='fact_settlement')
    op.drop_table('fact_settlement')
    # ### end Alembic commands ###
