"""add household setting table

Revision ID: abda6d99d27c
Revises: 7a027ff4174f
Create Date: 2026-08-29 19:17:29.985542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abda6d99d27c'
down_revision: Union[str, Sequence[str], None] = '7a027ff4174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_setting',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###

    # Manually added: seed a 50/50 default for every user that already
    # exists, so the table is never in a half-configured state. Plain SQL
    # rather than the ORM model, since models.py can change shape later
    # and this migration must keep running as written.
    op.execute(
        """
        INSERT INTO household_setting (user_id, share_pct)
        SELECT user_id, 0.5 FROM dim_user
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_setting')
    # ### end Alembic commands ###
