"""baseline: existing schema

Revision ID: b24c43f3c0f3
Revises: 
Create Date: 2026-08-22 16:29:10.713055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24c43f3c0f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('primary_category', sa.String(length=255), nullable=False),
    sa.Column('sub_category', sa.String(length=255), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('primary_category', 'sub_category', name='uq_category')
    )
    op.create_index(op.f('ix_dim_category_category_id'), 'dim_category', ['category_id'], unique=False)
    op.create_table('dim_payment_method',
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('is_credit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('payment_method_id'),
    sa.UniqueConstraint('method_name', 'institution', name='uq_payment_method')
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_dim_user_email'), 'dim_user', ['email'], unique=True)
    op.create_index(op.f('ix_dim_user_user_id'), 'dim_user', ['user_id'], unique=False)
    op.create_table('fact_expenditures',
    sa.Column('expenditure_id', sa.Integer(), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('current_installment', sa.Integer(), nullable=True),
    sa.Column('total_installments', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.category_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['dim_payment_method.payment_method_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('expenditure_id')
    )
    op.create_index(op.f('ix_fact_expenditures_expenditure_id'), 'fact_expenditures', ['expenditure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_expenditures_expenditure_id'), table_name='fact_expenditures')
    op.drop_table('fact_expenditures')
    op.drop_index(op.f('ix_dim_user_user_id'), table_name='dim_user')
    op.drop_index(op.f('ix_dim_user_email'), table_name='dim_user')
    op.drop_table('dim_user')
    op.drop_table('dim_payment_method')
    op.drop_index(op.f('ix_dim_category_category_id'), table_name='dim_category')
    op.drop_table('dim_category')
    # ### end Alembic commands ###
