"""add fact_expenditure_split table

Revision ID: c733614c3aa4
Revises: abda6d99d27c
Create Date: 2026-08-29 20:01:31.949739

"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from split_logic import split_amount


# revision identifiers, used by Alembic.
revision: str = 'c733614c3aa4'
down_revision: Union[str, Sequence[str], None] = 'abda6d99d27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_expenditure_split',
    sa.Column('expenditure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('split_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['expenditure_id'], ['fact_expenditures.expenditure_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('expenditure_id', 'user_id')
    )
    # ### end Alembic commands ###

    # Manually added: backfill allocation rows for every expenditure that
    # existed before this table did.
    bind = op.get_bind()

    household = bind.execute(
        sa.text("SELECT user_id, share_pct FROM household_setting ORDER BY user_id")
    ).fetchall()
    household_user_ids = [row.user_id for row in household]
    household_shares = [row.share_pct for row in household]

    # Shared expenses: split by the current household ratio.
    shared_expenditures = bind.execute(
        sa.text("SELECT expenditure_id, price FROM fact_expenditures WHERE is_shared = true")
    ).fetchall()

    for exp in shared_expenditures:
        amounts = split_amount(Decimal(exp.price), household_shares)
        for user_id, share_pct, share_amount in zip(household_user_ids, household_shares, amounts):
            bind.execute(
                sa.text(
                    """
                    INSERT INTO fact_expenditure_split
                        (expenditure_id, user_id, share_pct, share_amount, split_source)
                    VALUES (:expenditure_id, :user_id, :share_pct, :share_amount, 'household_default')
                    """
                ),
                {
                    "expenditure_id": exp.expenditure_id,
                    "user_id": user_id,
                    "share_pct": share_pct,
                    "share_amount": share_amount
                },
            )

    # Personal expenses: one row, 100% to whoever paid.
    personal_expenditures = bind.execute(
        sa.text("SELECT expenditure_id, price, user_id FROM fact_expenditures WHERE is_shared = false")
    ).fetchall()

    for exp in personal_expenditures:
        bind.execute(
            sa.text(
                """
                    INSERT INTO fact_expenditure_split
                        (expenditure_id, user_id, share_pct, share_amount, split_source)
                    VALUES (:expenditure_id, :user_id, 1.0, :share_amount, 'not_shared')
                """
            ),
            {
                "expenditure_id": exp.expenditure_id,
                "user_id": exp.user_id,
                "share_amount": exp.price,
            },
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_expenditure_split')
    # ### end Alembic commands ###
